FROM ubuntu:16.04

MAINTAINER Yuri Soffner <ysoffner@gmail.com>
#Base https://github.com/William-Yeh/docker-ansible/blob/master/ubuntu16.04/Dockerfile

RUN echo "===> Adding Ansible's PPA..."  && \
    echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main" | tee /etc/apt/sources.list.d/ansible.list           && \
    echo "deb-src http://ppa.launchpad.net/ansible/ansible/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/ansible.list    && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7BB9C367    && \
    DEBIAN_FRONTEND=noninteractive  apt-get update  && \
\
    echo "===> Installing Ansible..."  && \
    apt-get install -y ansible  && \
\
    echo "===> Installing handy tools (not absolutely required)..."  && \
    apt-get install -y python-pip              && \
    pip install --upgrade pywinrm docker       && \
    apt-get install -y sshpass openssh-client  && \
\
    echo "===> Removing Ansible PPA..."  && \
    rm -rf /var/lib/apt/lists/*  /etc/apt/sources.list.d/ansible.list  && \
\
    echo "===> Adding hosts for convenience..."  && \
    echo 'localhost' > /etc/ansible/hosts && \
\
    echo "===> Install Docker..."
ADD https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz /tmp

RUN tar -xvzf /tmp/docker-latest.tgz && \
    mv docker/* /usr/bin/ && \
    chmod +x /usr/bin/docker && \
    rm -f /tmp/docker-latest.tgz \


# default command: display Ansible version
# CMD [ "ansible-playbook", "--version" ]

CMD ["/sbin/init"]