version: '2'

services:
  ansible:
    privileged: true
    # build:
    #   context: .
    #   dockerfile: Dockerfile_ansible
    image: ansible
    container_name: ansible
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app